/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/licensedefault.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to
edit this template
 */
/**
 *
 * @author sss
 */
public class login extends javax.swing.JFrame {
 /**
 * Creates new form login
 */
 public login() {
 initComponents();
 }
 /**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is
always
 * regenerated by the Form Editor.
 */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">
 private void initComponents() {
 jPanel1 = new javax.swing.JPanel();
 uname = new javax.swing.JLabel();
 jLabel2 = new javax.swing.JLabel();
 u_name = new javax.swing.JTextField();
 p_word = new javax.swing.JTextField();
 jButton1 = new javax.swing.JButton();
 jButton2 = new javax.swing.JButton();
 ltext = new javax.swing.JLabel();
 jLabel3 = new javax.swing.JLabel();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
 uname.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
 uname.setText("USERNAME:");
 jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
 jLabel2.setText("PASSWORD:");
 jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
 jButton1.setText("LOGIN");
 jButton1.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jButton1ActionPerformed(evt);
 }
 });
 jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
 jButton2.setText("SIGN IN");
 jButton2.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jButton2ActionPerformed(evt);
 }
 });
 jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
 jLabel3.setText("BANKING MANAGEMENT SYSTEM");
 javax.swing.GroupLayout jPanel1Layout = new
javax.swing.GroupLayout(jPanel1);
 jPanel1.setLayout(jPanel1Layout);
 jPanel1Layout.setHorizontalGroup(

jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEAD
ING)
 .addGroup(jPanel1Layout.createSequentialGroup()
 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
Short.MAX_VALUE)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Align
ment.LEADING)
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
jPanel1Layout.createSequentialGroup()
 .addComponent(ltext,
javax.swing.GroupLayout.PREFERRED_SIZE, 201,
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addGap(44, 44, 44))
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
jPanel1Layout.createSequentialGroup()
 .addComponent(jButton1)
 .addGap(593, 593, 593))))
 .addGroup(jPanel1Layout.createSequentialGroup()

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Align
ment.LEADING)
 .addGroup(jPanel1Layout.createSequentialGroup()
 .addGap(195, 195, 195)
 .addComponent(jLabel3))
 .addGroup(jPanel1Layout.createSequentialGroup()
 .addGap(277, 277, 277)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Align
ment.TRAILING)
 .addComponent(uname)
 .addComponent(jLabel2))
 .addGap(24, 24, 24)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Align
ment.LEADING)
 .addComponent(jButton2)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Align
ment.LEADING, false)
 .addComponent(p_word,
javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
 .addComponent(u_name)))))
 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
Short.MAX_VALUE))
 );
 jPanel1Layout.setVerticalGroup(

jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEAD
ING)
 .addGroup(jPanel1Layout.createSequentialGroup()
 .addGap(58, 58, 58)
 .addComponent(jLabel3)
 .addGap(38, 38, 38)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Align
ment.TRAILING)
 .addGroup(jPanel1Layout.createSequentialGroup()

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Align
ment.BASELINE)
 .addComponent(u_name,
javax.swing.GroupLayout.PREFERRED_SIZE, 32,
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addComponent(uname))
 .addGap(38, 38, 38)
 .addComponent(p_word,
javax.swing.GroupLayout.PREFERRED_SIZE, 41,
javax.swing.GroupLayout.PREFERRED_SIZE))
 .addComponent(jLabel2))

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Align
ment.LEADING)
 .addGroup(jPanel1Layout.createSequentialGroup()

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
66, Short.MAX_VALUE)
 .addComponent(ltext,
javax.swing.GroupLayout.PREFERRED_SIZE, 91,
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addGap(57, 57, 57))
 .addGroup(jPanel1Layout.createSequentialGroup()
 .addGap(45, 45, 45)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Align
ment.BASELINE)
 .addComponent(jButton1)
 .addComponent(jButton2))
 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
Short.MAX_VALUE))))
 );
 javax.swing.GroupLayout layout = new
javax.swing.GroupLayout(getContentPane());
 getContentPane().setLayout(layout);
 layout.setHorizontalGroup(

layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
layout.createSequentialGroup()
 .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
 .addContainerGap())
 );
 layout.setVerticalGroup(

layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(layout.createSequentialGroup()
 .addContainerGap()
 .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
 .addContainerGap())
 );
 pack();
 }// </editor-fold>
 private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
 String u=u_name.getText();
String p=p_word.getText();
try
{
if(useraction.search(u,p))
{
navigation n =new navigation();
n.show();
dispose();
}
else
{
ltext.setText("Invalid Credentials");
}
}
catch(Exception e)
{
System.out.println(e);
} // TODO add your handling code here:
 }
 private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
newaccout ob =new newaccout();
ob.show();
dispose(); // TODO add your handling code here:
 }
 /**
 * @param args the command line arguments
 */
 public static void main(String args[]) {
 /* Set the Nimbus look and feel */
 //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
(optional) ">
 /* If Nimbus (introduced in Java SE 6) is not available, stay with the
default look and feel.
 * For details see
http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
 */
 try {
 for (javax.swing.UIManager.LookAndFeelInfo info :
javax.swing.UIManager.getInstalledLookAndFeels()) {
 if ("Nimbus".equals(info.getName())) {
 javax.swing.UIManager.setLookAndFeel(info.getClassName());
 break;
 }
 }
 } catch (ClassNotFoundException ex) {

java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging
.Level.SEVERE, null, ex);
 } catch (InstantiationException ex) {

java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging
.Level.SEVERE, null, ex);
 } catch (IllegalAccessException ex) {

java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging
.Level.SEVERE, null, ex);
 } catch (javax.swing.UnsupportedLookAndFeelException ex) {

java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging
.Level.SEVERE, null, ex);
 }
 //</editor-fold>
 /* Create and display the form */
 java.awt.EventQueue.invokeLater(new Runnable() {
 public void run() {
 new login().setVisible(true);
 }
 });
 }
 // Variables declaration - do not modify
 private javax.swing.JButton jButton1;
 private javax.swing.JButton jButton2;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JLabel jLabel3;
 private javax.swing.JPanel jPanel1;
 private javax.swing.JLabel ltext;
 private javax.swing.JTextField p_word;
 private javax.swing.JTextField u_name;
 private javax.swing.JLabel uname;
 // End of variables declaration
} 
